MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-DiffAug-train-2022_02_11_01_04_16 -cfg ./src/configs/CIFAR10/SNGAN-DiffAug.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================1/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-DiffAug-train-2022_02_11_01_04_16 -cfg ./src/configs/CIFAR10/SNGAN-DiffAug.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================2/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-DiffAug-train-2022_02_11_01_04_16 -cfg ./src/configs/CIFAR10/SNGAN-DiffAug.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================3/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-DiffAug-train-2022_02_26_03_56_11 -cfg ./src/configs/CIFAR10/SNGAN-DiffAug.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================4/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-DiffAug-train-2022_02_26_03_56_11 -cfg ./src/configs/CIFAR10/SNGAN-DiffAug.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================5/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-DiffAug-train-2022_02_26_03_56_11 -cfg ./src/configs/CIFAR10/SNGAN-DiffAug.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================6/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-DiffAug-train-2022_02_11_01_08_37 -cfg ./src/configs/CIFAR10/SNGAN-DiffAug.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================7/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-DiffAug-train-2022_02_11_01_08_37 -cfg ./src/configs/CIFAR10/SNGAN-DiffAug.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================8/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-DiffAug-train-2022_02_11_01_08_37 -cfg ./src/configs/CIFAR10/SNGAN-DiffAug.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================9/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-ADA-train-2022_02_11_01_04_17 -cfg ./src/configs/CIFAR10/SNGAN-ADA.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================10/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-ADA-train-2022_02_11_01_04_17 -cfg ./src/configs/CIFAR10/SNGAN-ADA.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================11/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-ADA-train-2022_02_11_01_04_17 -cfg ./src/configs/CIFAR10/SNGAN-ADA.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================12/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-ADA-train-2022_02_11_01_06_35 -cfg ./src/configs/CIFAR10/SNGAN-ADA.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================13/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-ADA-train-2022_02_11_01_06_35 -cfg ./src/configs/CIFAR10/SNGAN-ADA.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================14/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-ADA-train-2022_02_11_01_06_35 -cfg ./src/configs/CIFAR10/SNGAN-ADA.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================15/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-ADA-train-2022_02_11_01_08_37 -cfg ./src/configs/CIFAR10/SNGAN-ADA.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================16/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-ADA-train-2022_02_11_01_08_37 -cfg ./src/configs/CIFAR10/SNGAN-ADA.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================17/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-ADA-train-2022_02_11_01_08_37 -cfg ./src/configs/CIFAR10/SNGAN-ADA.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================18/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-APA-train-2022_02_11_01_04_17 -cfg ./src/configs/CIFAR10/SNGAN-APA.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================19/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-APA-train-2022_02_11_01_04_17 -cfg ./src/configs/CIFAR10/SNGAN-APA.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================20/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-APA-train-2022_02_11_01_04_17 -cfg ./src/configs/CIFAR10/SNGAN-APA.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================21/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-APA-train-2022_02_11_01_06_35 -cfg ./src/configs/CIFAR10/SNGAN-APA.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================22/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-APA-train-2022_02_11_01_06_35 -cfg ./src/configs/CIFAR10/SNGAN-APA.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================23/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-APA-train-2022_02_11_01_06_35 -cfg ./src/configs/CIFAR10/SNGAN-APA.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================24/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-APA-train-2022_02_11_01_08_37 -cfg ./src/configs/CIFAR10/SNGAN-APA.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================25/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-APA-train-2022_02_11_01_08_37 -cfg ./src/configs/CIFAR10/SNGAN-APA.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================26/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-APA-train-2022_02_11_01_08_37 -cfg ./src/configs/CIFAR10/SNGAN-APA.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================27/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-LeCam-train-2022_02_11_01_04_17 -cfg ./src/configs/CIFAR10/SNGAN-LeCam.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================28/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-LeCam-train-2022_02_11_01_04_17 -cfg ./src/configs/CIFAR10/SNGAN-LeCam.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================29/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-LeCam-train-2022_02_11_01_04_17 -cfg ./src/configs/CIFAR10/SNGAN-LeCam.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================30/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-LeCam-train-2022_02_11_01_06_35 -cfg ./src/configs/CIFAR10/SNGAN-LeCam.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================31/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-LeCam-train-2022_02_11_01_06_35 -cfg ./src/configs/CIFAR10/SNGAN-LeCam.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================32/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-LeCam-train-2022_02_11_01_06_35 -cfg ./src/configs/CIFAR10/SNGAN-LeCam.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================33/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-LeCam-train-2022_02_11_07_00_48 -cfg ./src/configs/CIFAR10/SNGAN-LeCam.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================34/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-LeCam-train-2022_02_11_07_00_48 -cfg ./src/configs/CIFAR10/SNGAN-LeCam.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================35/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-LeCam-train-2022_02_11_07_00_48 -cfg ./src/configs/CIFAR10/SNGAN-LeCam.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================36/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-DiffAug-LeCam-train-2022_02_11_01_04_17 -cfg ./src/configs/CIFAR10/SNGAN-DiffAug-LeCam.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================37/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-DiffAug-LeCam-train-2022_02_11_01_04_17 -cfg ./src/configs/CIFAR10/SNGAN-DiffAug-LeCam.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================38/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-DiffAug-LeCam-train-2022_02_11_01_04_17 -cfg ./src/configs/CIFAR10/SNGAN-DiffAug-LeCam.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================39/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-DiffAug-LeCam-train-2022_02_11_07_34_06 -cfg ./src/configs/CIFAR10/SNGAN-DiffAug-LeCam.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================40/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-DiffAug-LeCam-train-2022_02_11_07_34_06 -cfg ./src/configs/CIFAR10/SNGAN-DiffAug-LeCam.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================41/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-DiffAug-LeCam-train-2022_02_11_07_34_06 -cfg ./src/configs/CIFAR10/SNGAN-DiffAug-LeCam.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================42/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-DiffAug-LeCam-train-2022_02_11_07_38_06 -cfg ./src/configs/CIFAR10/SNGAN-DiffAug-LeCam.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================43/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-DiffAug-LeCam-train-2022_02_11_07_38_06 -cfg ./src/configs/CIFAR10/SNGAN-DiffAug-LeCam.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================44/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-DiffAug-LeCam-train-2022_02_11_07_38_06 -cfg ./src/configs/CIFAR10/SNGAN-DiffAug-LeCam.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================45/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-DiffAug-train-2022_02_11_07_19_25 -cfg ./src/configs/CIFAR10/BigGAN-DiffAug.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================46/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-DiffAug-train-2022_02_11_07_19_25 -cfg ./src/configs/CIFAR10/BigGAN-DiffAug.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================47/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-DiffAug-train-2022_02_11_07_19_25 -cfg ./src/configs/CIFAR10/BigGAN-DiffAug.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================48/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-DiffAug-train-2022_02_11_07_21_33 -cfg ./src/configs/CIFAR10/BigGAN-DiffAug.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================49/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-DiffAug-train-2022_02_11_07_21_33 -cfg ./src/configs/CIFAR10/BigGAN-DiffAug.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================50/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-DiffAug-train-2022_02_11_07_21_33 -cfg ./src/configs/CIFAR10/BigGAN-DiffAug.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================51/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-DiffAug-train-2022_02_11_07_23_15 -cfg ./src/configs/CIFAR10/BigGAN-DiffAug.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================52/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-DiffAug-train-2022_02_11_07_23_15 -cfg ./src/configs/CIFAR10/BigGAN-DiffAug.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================53/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-DiffAug-train-2022_02_11_07_23_15 -cfg ./src/configs/CIFAR10/BigGAN-DiffAug.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================54/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-ADA-train-2022_02_11_07_19_25 -cfg ./src/configs/CIFAR10/BigGAN-ADA.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================55/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-ADA-train-2022_02_11_07_19_25 -cfg ./src/configs/CIFAR10/BigGAN-ADA.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================56/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-ADA-train-2022_02_11_07_19_25 -cfg ./src/configs/CIFAR10/BigGAN-ADA.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================57/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-ADA-train-2022_02_11_07_21_38 -cfg ./src/configs/CIFAR10/BigGAN-ADA.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================58/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-ADA-train-2022_02_11_07_21_38 -cfg ./src/configs/CIFAR10/BigGAN-ADA.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================59/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-ADA-train-2022_02_11_07_21_38 -cfg ./src/configs/CIFAR10/BigGAN-ADA.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================60/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-ADA-train-2022_02_12_18_54_39 -cfg ./src/configs/CIFAR10/BigGAN-ADA.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================61/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-ADA-train-2022_02_12_18_54_39 -cfg ./src/configs/CIFAR10/BigGAN-ADA.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================62/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-ADA-train-2022_02_12_18_54_39 -cfg ./src/configs/CIFAR10/BigGAN-ADA.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================63/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-APA-train-2022_02_11_07_19_25 -cfg ./src/configs/CIFAR10/BigGAN-APA.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================64/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-APA-train-2022_02_11_07_19_25 -cfg ./src/configs/CIFAR10/BigGAN-APA.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================65/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-APA-train-2022_02_11_07_19_25 -cfg ./src/configs/CIFAR10/BigGAN-APA.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================66/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-APA-train-2022_02_11_07_21_41 -cfg ./src/configs/CIFAR10/BigGAN-APA.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================67/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-APA-train-2022_02_11_07_21_41 -cfg ./src/configs/CIFAR10/BigGAN-APA.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================68/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-APA-train-2022_02_11_07_21_41 -cfg ./src/configs/CIFAR10/BigGAN-APA.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================69/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-APA-train-2022_02_11_07_23_20 -cfg ./src/configs/CIFAR10/BigGAN-APA.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================70/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-APA-train-2022_02_11_07_23_20 -cfg ./src/configs/CIFAR10/BigGAN-APA.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================71/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-APA-train-2022_02_11_07_23_20 -cfg ./src/configs/CIFAR10/BigGAN-APA.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================72/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-LeCam-train-2022_02_03_11_05_56 -cfg ./src/configs/CIFAR10/BigGAN-LeCam.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================73/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-LeCam-train-2022_02_03_11_05_56 -cfg ./src/configs/CIFAR10/BigGAN-LeCam.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================74/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-LeCam-train-2022_02_03_11_05_56 -cfg ./src/configs/CIFAR10/BigGAN-LeCam.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================75/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=3 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-LeCam-train-2022_02_02_21_57_59 -cfg ./src/configs/CIFAR10/BigGAN-LeCam.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================76/135 completed =============
