python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-ContraGAN-train-2022_02_24_06_14_56 -cfg ./src/configs/Grandpa_ImageNet/ContraGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================17/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-ContraGAN-train-2022_02_24_06_14_56 -cfg ./src/configs/Grandpa_ImageNet/ContraGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================18/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-ContraGAN-train-2022_02_25_01_29_06 -cfg ./src/configs/Grandpa_ImageNet/ContraGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================19/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-ContraGAN-train-2022_02_25_01_29_06 -cfg ./src/configs/Grandpa_ImageNet/ContraGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================20/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-ContraGAN-train-2022_02_25_01_29_06 -cfg ./src/configs/Grandpa_ImageNet/ContraGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================21/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-ReACGAN-train-2022_02_20_13_47_57 -cfg ./src/configs/Grandpa_ImageNet/ReACGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================22/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-ReACGAN-train-2022_02_20_13_47_57 -cfg ./src/configs/Grandpa_ImageNet/ReACGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================23/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-ReACGAN-train-2022_02_20_13_47_57 -cfg ./src/configs/Grandpa_ImageNet/ReACGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================24/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-ReACGAN-train-2022_02_23_20_54_25 -cfg ./src/configs/Grandpa_ImageNet/ReACGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================25/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-ReACGAN-train-2022_02_23_20_54_25 -cfg ./src/configs/Grandpa_ImageNet/ReACGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================26/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-ReACGAN-train-2022_02_23_20_54_25 -cfg ./src/configs/Grandpa_ImageNet/ReACGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================27/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-StyleGAN2-SPD-train-2022_02_24_13_43_37 -cfg ./src/configs/Grandpa_ImageNet/StyleGAN2-SPD.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================28/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-StyleGAN2-SPD-train-2022_02_24_13_43_37 -cfg ./src/configs/Grandpa_ImageNet/StyleGAN2-SPD.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================29/36 completed =============

python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /home/mgkang/data/CIFAR10 -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN3-t-ADA-train-2022_03_10_15_38_39 -cfg ./src/configs/CIFAR10/StyleGAN3-t-ADA.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================226/243 completed =============
python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /home/mgkang/data/CIFAR10 -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN3-t-ADA-train-2022_03_10_15_38_39 -cfg ./src/configs/CIFAR10/StyleGAN3-t-ADA.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================227/243 completed =============
python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /home/mgkang/data/CIFAR10 -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN3-t-ADA-train-2022_03_10_15_38_39 -cfg ./src/configs/CIFAR10/StyleGAN3-t-ADA.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================228/243 completed =============
python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /home/mgkang/data/CIFAR10 -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN3-t-ADA-train-2022_03_11_13_48_00 -cfg ./src/configs/CIFAR10/StyleGAN3-t-ADA.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================229/243 completed =============
python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /home/mgkang/data/CIFAR10 -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN3-t-ADA-train-2022_03_11_13_48_00 -cfg ./src/configs/CIFAR10/StyleGAN3-t-ADA.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================230/243 completed =============
python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /home/mgkang/data/CIFAR10 -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN3-t-ADA-train-2022_03_11_13_48_00 -cfg ./src/configs/CIFAR10/StyleGAN3-t-ADA.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================231/243 completed =============
