python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-BigGAN-train-2022_02_23_16_26_09 -cfg ./src/configs/Papa_ImageNet/BigGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================14/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-BigGAN-train-2022_02_23_16_26_09 -cfg ./src/configs/Papa_ImageNet/BigGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================15/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-ContraGAN-train-2022_02_18_16_43_49 -cfg ./src/configs/Papa_ImageNet/ContraGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================16/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-ContraGAN-train-2022_02_18_16_43_49 -cfg ./src/configs/Papa_ImageNet/ContraGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================17/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-ContraGAN-train-2022_02_18_16_43_49 -cfg ./src/configs/Papa_ImageNet/ContraGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================18/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-ContraGAN-train-2022_02_28_07_20_51 -cfg ./src/configs/Papa_ImageNet/ContraGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================19/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-ContraGAN-train-2022_02_28_07_20_51 -cfg ./src/configs/Papa_ImageNet/ContraGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================20/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-ContraGAN-train-2022_02_28_07_20_51 -cfg ./src/configs/Papa_ImageNet/ContraGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================21/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-ReACGAN-train-2022_02_18_20_16_51 -cfg ./src/configs/Papa_ImageNet/ReACGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================22/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-ReACGAN-train-2022_02_18_20_16_51 -cfg ./src/configs/Papa_ImageNet/ReACGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================23/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-ReACGAN-train-2022_02_18_20_16_51 -cfg ./src/configs/Papa_ImageNet/ReACGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================24/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-ReACGAN-train-2022_02_21_15_09_16 -cfg ./src/configs/Papa_ImageNet/ReACGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================25/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-ReACGAN-train-2022_02_21_15_09_16 -cfg ./src/configs/Papa_ImageNet/ReACGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================26/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-StyleGAN3-t-SPD-train-2022_02_28_14_04_26 -cfg ./src/configs/Grandpa_ImageNet/StyleGAN3-t-SPD.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================34/36 completed =============
