python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Baby_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Baby_ImageNet/checkpoints/Baby_ImageNet-BigGAN-train-2022_02_19_21_22_58 -cfg ./src/configs/Baby_ImageNet/BigGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================14/39 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Baby_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Baby_ImageNet/checkpoints/Baby_ImageNet-BigGAN-train-2022_02_19_21_22_58 -cfg ./src/configs/Baby_ImageNet/BigGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================15/39 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Baby_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Baby_ImageNet/checkpoints/Baby_ImageNet-ContraGAN-train-2022_02_14_00_53_32 -cfg ./src/configs/Baby_ImageNet/ContraGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================16/39 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Baby_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Baby_ImageNet/checkpoints/Baby_ImageNet-ContraGAN-train-2022_02_14_00_53_32 -cfg ./src/configs/Baby_ImageNet/ContraGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================17/39 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Baby_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Baby_ImageNet/checkpoints/Baby_ImageNet-ContraGAN-train-2022_02_14_00_53_32 -cfg ./src/configs/Baby_ImageNet/ContraGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================18/39 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Baby_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Baby_ImageNet/checkpoints/Baby_ImageNet-ContraGAN-train-2022_02_21_19_55_51 -cfg ./src/configs/Baby_ImageNet/ContraGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================19/39 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Baby_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Baby_ImageNet/checkpoints/Baby_ImageNet-ContraGAN-train-2022_02_21_19_55_51 -cfg ./src/configs/Baby_ImageNet/ContraGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================20/39 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Baby_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Baby_ImageNet/checkpoints/Baby_ImageNet-ContraGAN-train-2022_02_21_19_55_51 -cfg ./src/configs/Baby_ImageNet/ContraGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================21/39 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Baby_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Baby_ImageNet/checkpoints/Baby_ImageNet-ReACGAN-train-2022_02_14_12_14_40 -cfg ./src/configs/Baby_ImageNet/ReACGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================22/39 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Baby_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Baby_ImageNet/checkpoints/Baby_ImageNet-ReACGAN-train-2022_02_14_12_14_40 -cfg ./src/configs/Baby_ImageNet/ReACGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================23/39 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Baby_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Baby_ImageNet/checkpoints/Baby_ImageNet-ReACGAN-train-2022_02_14_12_14_40 -cfg ./src/configs/Baby_ImageNet/ReACGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================24/39 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Baby_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Baby_ImageNet/checkpoints/Baby_ImageNet-ReACGAN-train-2022_02_19_21_28_54 -cfg ./src/configs/Baby_ImageNet/ReACGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================25/39 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Baby_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Baby_ImageNet/checkpoints/Baby_ImageNet-ReACGAN-train-2022_02_19_21_28_54 -cfg ./src/configs/Baby_ImageNet/ReACGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================26/39 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-StyleGAN2-SPD-train-2022_02_24_15_37_30 -cfg ./src/configs/Grandpa_ImageNet/StyleGAN2-SPD.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================31/36 completed =============
