python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 256 -std_step 256 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-SNGAN-train-2022_03_06_11_49_19 -cfg ./src/configs/Grandpa_ImageNet/SNGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================4/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 256 -std_step 256 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-SNGAN-train-2022_03_06_11_49_19 -cfg ./src/configs/Grandpa_ImageNet/SNGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================5/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 256 -std_step 256 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-SNGAN-train-2022_03_06_11_49_19 -cfg ./src/configs/Grandpa_ImageNet/SNGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================6/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 256 -std_step 256 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-SAGAN-train-2022_03_08_03_19_50 -cfg ./src/configs/Grandpa_ImageNet/SAGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================7/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 256 -std_step 256 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-SAGAN-train-2022_03_08_03_19_50 -cfg ./src/configs/Grandpa_ImageNet/SAGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================8/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 256 -std_step 256 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-SAGAN-train-2022_03_08_03_19_50 -cfg ./src/configs/Grandpa_ImageNet/SAGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================9/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-BigGAN-train-2022_02_25_04_46_42 -cfg ./src/configs/Grandpa_ImageNet/BigGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================10/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-BigGAN-train-2022_02_25_04_46_42 -cfg ./src/configs/Grandpa_ImageNet/BigGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================11/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-BigGAN-train-2022_02_25_04_46_42 -cfg ./src/configs/Grandpa_ImageNet/BigGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================12/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-BigGAN-train-2022_02_24_20_18_33 -cfg ./src/configs/Grandpa_ImageNet/BigGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================13/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-BigGAN-train-2022_02_24_20_18_33 -cfg ./src/configs/Grandpa_ImageNet/BigGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================14/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-BigGAN-train-2022_02_24_20_18_33 -cfg ./src/configs/Grandpa_ImageNet/BigGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================15/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-ContraGAN-train-2022_02_24_06_14_56 -cfg ./src/configs/Grandpa_ImageNet/ContraGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================16/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-StyleGAN3-t-SPD-train-2022_02_28_14_04_26 -cfg ./src/configs/Grandpa_ImageNet/StyleGAN3-t-SPD.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================36/36 completed =============

python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /home/mgkang/data/CIFAR10 -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN3-r-ADA-train-2022_03_11_00_16_03 -cfg ./src/configs/CIFAR10/StyleGAN3-r-ADA.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================232/243 completed =============
python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /home/mgkang/data/CIFAR10 -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN3-r-ADA-train-2022_03_11_00_16_03 -cfg ./src/configs/CIFAR10/StyleGAN3-r-ADA.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================233/243 completed =============
python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /home/mgkang/data/CIFAR10 -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN3-r-ADA-train-2022_03_11_00_16_03 -cfg ./src/configs/CIFAR10/StyleGAN3-r-ADA.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================234/243 completed =============
