python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Baby_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Baby_ImageNet/checkpoints/Baby_ImageNet-ReACGAN-train-2022_02_19_21_28_54 -cfg ./src/configs/Baby_ImageNet/ReACGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================27/39 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Baby_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Baby_ImageNet/checkpoints/Baby_ImageNet-StyleGAN2-SPD-train-2022_02_23_22_28_56 -cfg ./src/configs/Baby_ImageNet/StyleGAN2-SPD.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================28/39 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Baby_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Baby_ImageNet/checkpoints/Baby_ImageNet-StyleGAN2-SPD-train-2022_02_23_22_28_56 -cfg ./src/configs/Baby_ImageNet/StyleGAN2-SPD.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================29/39 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Baby_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Baby_ImageNet/checkpoints/Baby_ImageNet-StyleGAN2-SPD-train-2022_02_23_22_28_56 -cfg ./src/configs/Baby_ImageNet/StyleGAN2-SPD.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================30/39 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Baby_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Baby_ImageNet/checkpoints/Baby_ImageNet-StyleGAN2-SPD-train-2022_02_23_22_26_17 -cfg ./src/configs/Baby_ImageNet/StyleGAN2-SPD.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================31/39 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Baby_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Baby_ImageNet/checkpoints/Baby_ImageNet-StyleGAN2-SPD-train-2022_02_23_22_26_17 -cfg ./src/configs/Baby_ImageNet/StyleGAN2-SPD.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================32/39 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Baby_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Baby_ImageNet/checkpoints/Baby_ImageNet-StyleGAN2-SPD-train-2022_02_23_22_26_17 -cfg ./src/configs/Baby_ImageNet/StyleGAN2-SPD.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================33/39 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Baby_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Baby_ImageNet/checkpoints/Baby_ImageNet-StyleGAN2-SPD-train-2022_02_25_10_37_05 -cfg ./src/configs/Baby_ImageNet/StyleGAN2-SPD.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================34/39 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Baby_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Baby_ImageNet/checkpoints/Baby_ImageNet-StyleGAN2-SPD-train-2022_02_25_10_37_05 -cfg ./src/configs/Baby_ImageNet/StyleGAN2-SPD.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================35/39 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Baby_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Baby_ImageNet/checkpoints/Baby_ImageNet-StyleGAN2-SPD-train-2022_02_25_10_37_05 -cfg ./src/configs/Baby_ImageNet/StyleGAN2-SPD.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================36/39 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Baby_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Baby_ImageNet/checkpoints/Baby_ImageNet-StyleGAN3-t-SPD-train-2022_02_14_19_49_57 -cfg ./src/configs/Baby_ImageNet/StyleGAN3-t-SPD.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================37/39 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Baby_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Baby_ImageNet/checkpoints/Baby_ImageNet-StyleGAN3-t-SPD-train-2022_02_14_19_49_57 -cfg ./src/configs/Baby_ImageNet/StyleGAN3-t-SPD.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================38/39 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Baby_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Baby_ImageNet/checkpoints/Baby_ImageNet-StyleGAN3-t-SPD-train-2022_02_14_19_49_57 -cfg ./src/configs/Baby_ImageNet/StyleGAN3-t-SPD.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================39/39 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-StyleGAN2-SPD-train-2022_02_24_15_37_30 -cfg ./src/configs/Grandpa_ImageNet/StyleGAN2-SPD.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================32/36 completed =============
