python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-ReACGAN-train-2022_02_21_15_09_16 -cfg ./src/configs/Papa_ImageNet/ReACGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================27/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-StyleGAN2-SPD-train-2022_02_18_19_49_49 -cfg ./src/configs/Papa_ImageNet/StyleGAN2-SPD.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================28/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-StyleGAN2-SPD-train-2022_02_18_19_49_49 -cfg ./src/configs/Papa_ImageNet/StyleGAN2-SPD.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================29/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-StyleGAN2-SPD-train-2022_02_18_19_49_49 -cfg ./src/configs/Papa_ImageNet/StyleGAN2-SPD.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================30/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-StyleGAN2-SPD-train-2022_02_20_14_40_08 -cfg ./src/configs/Papa_ImageNet/StyleGAN2-SPD.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================31/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-StyleGAN2-SPD-train-2022_02_20_14_40_08 -cfg ./src/configs/Papa_ImageNet/StyleGAN2-SPD.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================32/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-StyleGAN2-SPD-train-2022_02_20_14_40_08 -cfg ./src/configs/Papa_ImageNet/StyleGAN2-SPD.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================33/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-StyleGAN3-t-SPD-train-2022_02_24_19_24_04 -cfg ./src/configs/Papa_ImageNet/StyleGAN3-t-SPD.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================34/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-StyleGAN3-t-SPD-train-2022_02_24_19_24_04 -cfg ./src/configs/Papa_ImageNet/StyleGAN3-t-SPD.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================35/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-StyleGAN3-t-SPD-train-2022_02_24_19_24_04 -cfg ./src/configs/Papa_ImageNet/StyleGAN3-t-SPD.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================36/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 256 -std_step 256 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-SNGAN-train-2022_03_06_10_19_17 -cfg ./src/configs/Grandpa_ImageNet/SNGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================1/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 256 -std_step 256 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-SNGAN-train-2022_03_06_10_19_17 -cfg ./src/configs/Grandpa_ImageNet/SNGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================2/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 256 -std_step 256 -best --seed 1234 -ifid -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-SNGAN-train-2022_03_06_10_19_17 -cfg ./src/configs/Grandpa_ImageNet/SNGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================3/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-StyleGAN3-t-SPD-train-2022_02_28_14_04_26 -cfg ./src/configs/Grandpa_ImageNet/StyleGAN3-t-SPD.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================35/36 completed =============
