MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-train-2022_01_24_23_51_10 -cfg ./src/configs/CIFAR10/StyleGAN2.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================153/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ReACGAN-TAC-train-2022_01_26_10_50_05 -cfg ./src/configs/CIFAR10/ReACGAN-TAC.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================154/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ReACGAN-TAC-train-2022_01_26_10_50_05 -cfg ./src/configs/CIFAR10/ReACGAN-TAC.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================155/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ReACGAN-TAC-train-2022_01_26_10_50_05 -cfg ./src/configs/CIFAR10/ReACGAN-TAC.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================156/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ReACGAN-TAC-train-2022_01_26_10_52_15 -cfg ./src/configs/CIFAR10/ReACGAN-TAC.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================157/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ReACGAN-TAC-train-2022_01_26_10_52_15 -cfg ./src/configs/CIFAR10/ReACGAN-TAC.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================158/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ReACGAN-TAC-train-2022_01_26_10_52_15 -cfg ./src/configs/CIFAR10/ReACGAN-TAC.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================159/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ReACGAN-TAC-train-2022_01_26_10_52_54 -cfg ./src/configs/CIFAR10/ReACGAN-TAC.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================160/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ReACGAN-TAC-train-2022_01_26_10_52_54 -cfg ./src/configs/CIFAR10/ReACGAN-TAC.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================161/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ReACGAN-TAC-train-2022_01_26_10_52_54 -cfg ./src/configs/CIFAR10/ReACGAN-TAC.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================162/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-D2DCE-train-2022_01_26_10_54_47 -cfg ./src/configs/CIFAR10/StyleGAN2-D2DCE.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================163/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-D2DCE-train-2022_01_26_10_54_47 -cfg ./src/configs/CIFAR10/StyleGAN2-D2DCE.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================164/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-D2DCE-train-2022_01_26_10_54_47 -cfg ./src/configs/CIFAR10/StyleGAN2-D2DCE.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================165/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-D2DCE-train-2022_01_26_10_56_55 -cfg ./src/configs/CIFAR10/StyleGAN2-D2DCE.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================166/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-D2DCE-train-2022_01_26_10_56_55 -cfg ./src/configs/CIFAR10/StyleGAN2-D2DCE.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================167/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-D2DCE-train-2022_01_26_10_56_55 -cfg ./src/configs/CIFAR10/StyleGAN2-D2DCE.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================168/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-D2DCE-train-2022_02_14_18_32_44 -cfg ./src/configs/CIFAR10/StyleGAN2-D2DCE.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================169/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-D2DCE-train-2022_02_14_18_32_44 -cfg ./src/configs/CIFAR10/StyleGAN2-D2DCE.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================170/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-D2DCE-train-2022_02_14_18_32_44 -cfg ./src/configs/CIFAR10/StyleGAN2-D2DCE.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================171/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Deep-train-2022_02_02_21_48_16 -cfg ./src/configs/CIFAR10/BigGAN-Deep.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================172/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Deep-train-2022_02_02_21_48_16 -cfg ./src/configs/CIFAR10/BigGAN-Deep.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================173/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Deep-train-2022_02_02_21_48_16 -cfg ./src/configs/CIFAR10/BigGAN-Deep.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================174/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Deep-train-2022_02_14_18_23_41 -cfg ./src/configs/CIFAR10/BigGAN-Deep.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================175/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Deep-train-2022_02_14_18_23_41 -cfg ./src/configs/CIFAR10/BigGAN-Deep.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================176/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Deep-train-2022_02_14_18_23_41 -cfg ./src/configs/CIFAR10/BigGAN-Deep.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================177/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Deep-train-2022_02_02_21_50_43 -cfg ./src/configs/CIFAR10/BigGAN-Deep.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================178/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Deep-train-2022_02_02_21_50_43 -cfg ./src/configs/CIFAR10/BigGAN-Deep.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================179/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Deep-train-2022_02_02_21_50_43 -cfg ./src/configs/CIFAR10/BigGAN-Deep.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================180/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Deep-train-2022_02_02_21_56_10 -cfg ./src/configs/CIFAR10/BigGAN-Deep-StudioGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================181/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Deep-train-2022_02_02_21_56_10 -cfg ./src/configs/CIFAR10/BigGAN-Deep-StudioGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================182/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Deep-train-2022_02_02_21_56_10 -cfg ./src/configs/CIFAR10/BigGAN-Deep-StudioGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================183/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Deep-train-2022_02_02_21_56_49 -cfg ./src/configs/CIFAR10/BigGAN-Deep-StudioGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================184/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Deep-train-2022_02_02_21_56_49 -cfg ./src/configs/CIFAR10/BigGAN-Deep-StudioGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================185/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Deep-train-2022_02_02_21_56_49 -cfg ./src/configs/CIFAR10/BigGAN-Deep-StudioGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================186/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Deep-train-2022_02_02_22_01_49 -cfg ./src/configs/CIFAR10/BigGAN-Deep-StudioGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================187/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Deep-train-2022_02_02_22_01_49 -cfg ./src/configs/CIFAR10/BigGAN-Deep-StudioGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================188/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Deep-train-2022_02_02_22_01_49 -cfg ./src/configs/CIFAR10/BigGAN-Deep-StudioGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================189/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-CR-train-2022_03_10_13_58_51 -cfg ./src/configs/CIFAR10/BigGAN-CR.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================190/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-CR-train-2022_03_10_13_58_51 -cfg ./src/configs/CIFAR10/BigGAN-CR.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================191/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-CR-train-2022_03_10_13_58_51 -cfg ./src/configs/CIFAR10/BigGAN-CR.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================192/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-CR-train-2022_03_10_14_18_45 -cfg ./src/configs/CIFAR10/BigGAN-CR.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================193/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-CR-train-2022_03_10_14_18_45 -cfg ./src/configs/CIFAR10/BigGAN-CR.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================194/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-CR-train-2022_03_10_14_18_45 -cfg ./src/configs/CIFAR10/BigGAN-CR.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================195/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-CR-train-2022_03_10_14_20_11 -cfg ./src/configs/CIFAR10/BigGAN-CR.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================196/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-CR-train-2022_03_10_14_20_11 -cfg ./src/configs/CIFAR10/BigGAN-CR.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================197/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-CR-train-2022_03_10_14_20_11 -cfg ./src/configs/CIFAR10/BigGAN-CR.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================198/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-ICR-train-2022_03_10_14_39_55 -cfg ./src/configs/CIFAR10/BigGAN-ICR.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================199/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-ICR-train-2022_03_10_14_39_55 -cfg ./src/configs/CIFAR10/BigGAN-ICR.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================200/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-ICR-train-2022_03_10_14_39_55 -cfg ./src/configs/CIFAR10/BigGAN-ICR.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================201/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-ICR-train-2022_03_10_14_40_49 -cfg ./src/configs/CIFAR10/BigGAN-ICR.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================202/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-ICR-train-2022_03_10_14_40_49 -cfg ./src/configs/CIFAR10/BigGAN-ICR.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================203/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-ICR-train-2022_03_10_14_40_49 -cfg ./src/configs/CIFAR10/BigGAN-ICR.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================204/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-ICR-train-2022_03_10_14_45_50 -cfg ./src/configs/CIFAR10/BigGAN-ICR.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================205/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-ICR-train-2022_03_10_14_45_50 -cfg ./src/configs/CIFAR10/BigGAN-ICR.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================206/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-ICR-train-2022_03_10_14_45_50 -cfg ./src/configs/CIFAR10/BigGAN-ICR.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================207/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-LOGAN-train-2022_03_12_04_15_22 -cfg ./src/configs/CIFAR10/LOGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================208/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-LOGAN-train-2022_03_12_04_15_22 -cfg ./src/configs/CIFAR10/LOGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================209/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-LOGAN-train-2022_03_12_04_15_22 -cfg ./src/configs/CIFAR10/LOGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================210/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-LOGAN-train-2022_03_12_04_15_26 -cfg ./src/configs/CIFAR10/LOGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================211/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-LOGAN-train-2022_03_12_04_15_26 -cfg ./src/configs/CIFAR10/LOGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================212/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-LOGAN-train-2022_03_12_04_15_26 -cfg ./src/configs/CIFAR10/LOGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================213/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-LOGAN-train-2022_03_12_04_15_31 -cfg ./src/configs/CIFAR10/LOGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================214/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-LOGAN-train-2022_03_12_04_15_31 -cfg ./src/configs/CIFAR10/LOGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================215/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-LOGAN-train-2022_03_12_04_15_31 -cfg ./src/configs/CIFAR10/LOGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================216/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ACGAN-Mod-Big-ADC-train-2022_03_10_14_23_09 -cfg ./src/configs/CIFAR10/ACGAN-Mod-Big-ADC.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================217/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ACGAN-Mod-Big-ADC-train-2022_03_10_14_23_09 -cfg ./src/configs/CIFAR10/ACGAN-Mod-Big-ADC.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================218/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ACGAN-Mod-Big-ADC-train-2022_03_10_14_23_09 -cfg ./src/configs/CIFAR10/ACGAN-Mod-Big-ADC.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================219/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ACGAN-Mod-Big-ADC-train-2022_03_10_14_28_26 -cfg ./src/configs/CIFAR10/ACGAN-Mod-Big-ADC.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================220/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ACGAN-Mod-Big-ADC-train-2022_03_10_14_28_26 -cfg ./src/configs/CIFAR10/ACGAN-Mod-Big-ADC.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================221/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ACGAN-Mod-Big-ADC-train-2022_03_10_14_28_26 -cfg ./src/configs/CIFAR10/ACGAN-Mod-Big-ADC.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================222/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ACGAN-Mod-Big-ADC-train-2022_03_10_14_29_10 -cfg ./src/configs/CIFAR10/ACGAN-Mod-Big-ADC.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================223/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ACGAN-Mod-Big-ADC-train-2022_03_10_14_29_10 -cfg ./src/configs/CIFAR10/ACGAN-Mod-Big-ADC.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================224/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ACGAN-Mod-Big-ADC-train-2022_03_10_14_29_10 -cfg ./src/configs/CIFAR10/ACGAN-Mod-Big-ADC.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================225/243 completed =============
# MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN3-t-ADA-train-2022_03_10_15_38_39 -cfg ./src/configs/CIFAR10/StyleGAN3-t-ADA.yaml --eval_backbone InceptionV3_tf  -metrics none
# echo ==================226/243 completed =============
# MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN3-t-ADA-train-2022_03_10_15_38_39 -cfg ./src/configs/CIFAR10/StyleGAN3-t-ADA.yaml --eval_backbone SwAV_torch  -metrics none
# echo ==================227/243 completed =============
# MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN3-t-ADA-train-2022_03_10_15_38_39 -cfg ./src/configs/CIFAR10/StyleGAN3-t-ADA.yaml --eval_backbone Swin-T_torch  -metrics none
# echo ==================228/243 completed =============
# MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN3-t-ADA-train-2022_03_11_13_48_00 -cfg ./src/configs/CIFAR10/StyleGAN3-t-ADA.yaml --eval_backbone InceptionV3_tf  -metrics none
# echo ==================229/243 completed =============
# MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN3-t-ADA-train-2022_03_11_13_48_00 -cfg ./src/configs/CIFAR10/StyleGAN3-t-ADA.yaml --eval_backbone SwAV_torch  -metrics none
# echo ==================230/243 completed =============
# MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN3-t-ADA-train-2022_03_11_13_48_00 -cfg ./src/configs/CIFAR10/StyleGAN3-t-ADA.yaml --eval_backbone Swin-T_torch  -metrics none
# echo ==================231/243 completed =============
# MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN3-r-ADA-train-2022_03_11_00_16_03 -cfg ./src/configs/CIFAR10/StyleGAN3-r-ADA.yaml --eval_backbone InceptionV3_tf  -metrics none
# echo ==================232/243 completed =============
# MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN3-r-ADA-train-2022_03_11_00_16_03 -cfg ./src/configs/CIFAR10/StyleGAN3-r-ADA.yaml --eval_backbone SwAV_torch  -metrics none
# echo ==================233/243 completed =============
# MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN3-r-ADA-train-2022_03_11_00_16_03 -cfg ./src/configs/CIFAR10/StyleGAN3-r-ADA.yaml --eval_backbone Swin-T_torch  -metrics none
# echo ==================234/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-Info-train-2022_03_10_19_55_02 -cfg ./src/configs/CIFAR10/SNGAN-Info.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================235/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-Info-train-2022_03_10_19_55_02 -cfg ./src/configs/CIFAR10/SNGAN-Info.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================236/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-Info-train-2022_03_10_19_55_02 -cfg ./src/configs/CIFAR10/SNGAN-Info.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================237/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-Info-train-2022_03_10_20_18_44 -cfg ./src/configs/CIFAR10/SNGAN-Info.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================238/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-Info-train-2022_03_10_20_18_44 -cfg ./src/configs/CIFAR10/SNGAN-Info.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================239/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-Info-train-2022_03_10_20_18_44 -cfg ./src/configs/CIFAR10/SNGAN-Info.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================240/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-Info-train-2022_03_10_20_23_37 -cfg ./src/configs/CIFAR10/SNGAN-Info.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================241/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-Info-train-2022_03_10_20_23_37 -cfg ./src/configs/CIFAR10/SNGAN-Info.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================242/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-Info-train-2022_03_10_20_23_37 -cfg ./src/configs/CIFAR10/SNGAN-Info.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================243/243 completed =============
