MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-LeCam-train-2022_02_02_21_57_59 -cfg ./src/configs/CIFAR10/BigGAN-LeCam.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================77/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-LeCam-train-2022_02_02_21_57_59 -cfg ./src/configs/CIFAR10/BigGAN-LeCam.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================78/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-LeCam-train-2022_02_03_11_07_25 -cfg ./src/configs/CIFAR10/BigGAN-LeCam.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================79/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-LeCam-train-2022_02_03_11_07_25 -cfg ./src/configs/CIFAR10/BigGAN-LeCam.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================80/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-LeCam-train-2022_02_03_11_07_25 -cfg ./src/configs/CIFAR10/BigGAN-LeCam.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================81/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-DiffAug-LeCam-train-2022_02_12_18_59_01 -cfg ./src/configs/CIFAR10/BigGAN-DiffAug-LeCam.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================82/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-DiffAug-LeCam-train-2022_02_12_18_59_01 -cfg ./src/configs/CIFAR10/BigGAN-DiffAug-LeCam.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================83/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-DiffAug-LeCam-train-2022_02_12_18_59_01 -cfg ./src/configs/CIFAR10/BigGAN-DiffAug-LeCam.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================84/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-DiffAug-LeCam-train-2022_02_12_19_02_10 -cfg ./src/configs/CIFAR10/BigGAN-DiffAug-LeCam.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================85/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-DiffAug-LeCam-train-2022_02_12_19_02_10 -cfg ./src/configs/CIFAR10/BigGAN-DiffAug-LeCam.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================86/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-DiffAug-LeCam-train-2022_02_12_19_02_10 -cfg ./src/configs/CIFAR10/BigGAN-DiffAug-LeCam.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================87/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-DiffAug-LeCam-train-2022_02_12_19_02_45 -cfg ./src/configs/CIFAR10/BigGAN-DiffAug-LeCam.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================88/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-DiffAug-LeCam-train-2022_02_12_19_02_45 -cfg ./src/configs/CIFAR10/BigGAN-DiffAug-LeCam.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================89/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-DiffAug-LeCam-train-2022_02_12_19_02_45 -cfg ./src/configs/CIFAR10/BigGAN-DiffAug-LeCam.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================90/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-DiffAug-train-2022_02_15_00_54_13 -cfg ./src/configs/CIFAR10/StyleGAN2-DiffAug.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================91/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-DiffAug-train-2022_02_15_00_54_13 -cfg ./src/configs/CIFAR10/StyleGAN2-DiffAug.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================92/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-DiffAug-train-2022_02_15_00_54_13 -cfg ./src/configs/CIFAR10/StyleGAN2-DiffAug.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================93/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-DiffAug-train-2022_02_15_00_57_43 -cfg ./src/configs/CIFAR10/StyleGAN2-DiffAug.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================94/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-DiffAug-train-2022_02_15_00_57_43 -cfg ./src/configs/CIFAR10/StyleGAN2-DiffAug.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================95/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-DiffAug-train-2022_02_15_00_57_43 -cfg ./src/configs/CIFAR10/StyleGAN2-DiffAug.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================96/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-DiffAug-train-2022_02_15_01_04_42 -cfg ./src/configs/CIFAR10/StyleGAN2-DiffAug.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================97/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-DiffAug-train-2022_02_15_01_04_42 -cfg ./src/configs/CIFAR10/StyleGAN2-DiffAug.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================98/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-DiffAug-train-2022_02_15_01_04_42 -cfg ./src/configs/CIFAR10/StyleGAN2-DiffAug.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================99/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-ADA-train-2022_02_15_00_55_43 -cfg ./src/configs/CIFAR10/StyleGAN2-ADA.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================100/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-ADA-train-2022_02_15_00_55_43 -cfg ./src/configs/CIFAR10/StyleGAN2-ADA.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================101/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-ADA-train-2022_02_15_00_55_43 -cfg ./src/configs/CIFAR10/StyleGAN2-ADA.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================102/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-ADA-train-2022_02_15_01_03_43 -cfg ./src/configs/CIFAR10/StyleGAN2-ADA.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================103/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-ADA-train-2022_02_15_01_03_43 -cfg ./src/configs/CIFAR10/StyleGAN2-ADA.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================104/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-ADA-train-2022_02_15_01_03_43 -cfg ./src/configs/CIFAR10/StyleGAN2-ADA.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================105/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-ADA-train-2022_02_15_01_04_41 -cfg ./src/configs/CIFAR10/StyleGAN2-ADA.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================106/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-ADA-train-2022_02_15_01_04_41 -cfg ./src/configs/CIFAR10/StyleGAN2-ADA.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================107/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-ADA-train-2022_02_15_01_04_41 -cfg ./src/configs/CIFAR10/StyleGAN2-ADA.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================108/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-APA-train-2022_02_02_22_00_43 -cfg ./src/configs/CIFAR10/StyleGAN2-APA.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================109/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-APA-train-2022_02_02_22_00_43 -cfg ./src/configs/CIFAR10/StyleGAN2-APA.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================110/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-APA-train-2022_02_02_22_00_43 -cfg ./src/configs/CIFAR10/StyleGAN2-APA.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================111/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-APA-train-2022_02_02_21_59_29 -cfg ./src/configs/CIFAR10/StyleGAN2-APA.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================112/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-APA-train-2022_02_02_21_59_29 -cfg ./src/configs/CIFAR10/StyleGAN2-APA.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================113/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-APA-train-2022_02_02_21_59_29 -cfg ./src/configs/CIFAR10/StyleGAN2-APA.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================114/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-APA-train-2022_02_02_22_00_13 -cfg ./src/configs/CIFAR10/StyleGAN2-APA.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================115/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-APA-train-2022_02_02_22_00_13 -cfg ./src/configs/CIFAR10/StyleGAN2-APA.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================116/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-APA-train-2022_02_02_22_00_13 -cfg ./src/configs/CIFAR10/StyleGAN2-APA.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================117/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-LeCam-train-2022_02_15_00_55_45 -cfg ./src/configs/CIFAR10/StyleGAN2-LeCam.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================118/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-LeCam-train-2022_02_15_00_55_45 -cfg ./src/configs/CIFAR10/StyleGAN2-LeCam.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================119/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-LeCam-train-2022_02_15_00_55_45 -cfg ./src/configs/CIFAR10/StyleGAN2-LeCam.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================120/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-LeCam-train-2022_02_15_01_04_11 -cfg ./src/configs/CIFAR10/StyleGAN2-LeCam.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================121/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-LeCam-train-2022_02_15_01_04_11 -cfg ./src/configs/CIFAR10/StyleGAN2-LeCam.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================122/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-LeCam-train-2022_02_15_01_04_11 -cfg ./src/configs/CIFAR10/StyleGAN2-LeCam.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================123/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-LeCam-train-2022_02_15_02_25_56 -cfg ./src/configs/CIFAR10/StyleGAN2-LeCam.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================124/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-LeCam-train-2022_02_15_02_25_56 -cfg ./src/configs/CIFAR10/StyleGAN2-LeCam.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================125/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-LeCam-train-2022_02_15_02_25_56 -cfg ./src/configs/CIFAR10/StyleGAN2-LeCam.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================126/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-DiffAug-LeCam-train-2022_02_15_00_55_45 -cfg ./src/configs/CIFAR10/StyleGAN2-DiffAug-LeCam.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================127/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-DiffAug-LeCam-train-2022_02_15_00_55_45 -cfg ./src/configs/CIFAR10/StyleGAN2-DiffAug-LeCam.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================128/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-DiffAug-LeCam-train-2022_02_15_00_55_45 -cfg ./src/configs/CIFAR10/StyleGAN2-DiffAug-LeCam.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================129/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-DiffAug-LeCam-train-2022_02_15_01_04_13 -cfg ./src/configs/CIFAR10/StyleGAN2-DiffAug-LeCam.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================130/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-DiffAug-LeCam-train-2022_02_15_01_04_13 -cfg ./src/configs/CIFAR10/StyleGAN2-DiffAug-LeCam.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================131/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-DiffAug-LeCam-train-2022_02_15_01_04_13 -cfg ./src/configs/CIFAR10/StyleGAN2-DiffAug-LeCam.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================132/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-DiffAug-LeCam-train-2022_02_15_02_38_10 -cfg ./src/configs/CIFAR10/StyleGAN2-DiffAug-LeCam.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================133/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-DiffAug-LeCam-train-2022_02_15_02_38_10 -cfg ./src/configs/CIFAR10/StyleGAN2-DiffAug-LeCam.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================134/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-DiffAug-LeCam-train-2022_02_15_02_38_10 -cfg ./src/configs/CIFAR10/StyleGAN2-DiffAug-LeCam.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================135/135 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-Info-train-2022_03_10_20_18_44 -cfg ./src/configs/CIFAR10/SNGAN-Info.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================240/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-Info-train-2022_03_10_20_23_37 -cfg ./src/configs/CIFAR10/SNGAN-Info.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================241/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-Info-train-2022_03_10_20_23_37 -cfg ./src/configs/CIFAR10/SNGAN-Info.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================242/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=4 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-Info-train-2022_03_10_20_23_37 -cfg ./src/configs/CIFAR10/SNGAN-Info.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================243/243 completed =============
