MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ACGAN-Mod-train-2022_03_06_02_22_36 -cfg ./src/configs/CIFAR10/ACGAN-Mod.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================77/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ACGAN-Mod-train-2022_03_06_02_22_36 -cfg ./src/configs/CIFAR10/ACGAN-Mod.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================78/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ACGAN-Mod-train-2022_03_06_02_24_19 -cfg ./src/configs/CIFAR10/ACGAN-Mod.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================79/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ACGAN-Mod-train-2022_03_06_02_24_19 -cfg ./src/configs/CIFAR10/ACGAN-Mod.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================80/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ACGAN-Mod-train-2022_03_06_02_24_19 -cfg ./src/configs/CIFAR10/ACGAN-Mod.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================81/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ACGAN-Mod-TAC-train-2022_03_06_02_20_59 -cfg ./src/configs/CIFAR10/ACGAN-Mod-TAC.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================82/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ACGAN-Mod-TAC-train-2022_03_06_02_20_59 -cfg ./src/configs/CIFAR10/ACGAN-Mod-TAC.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================83/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ACGAN-Mod-TAC-train-2022_03_06_02_20_59 -cfg ./src/configs/CIFAR10/ACGAN-Mod-TAC.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================84/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ACGAN-Mod-TAC-train-2022_03_06_02_22_58 -cfg ./src/configs/CIFAR10/ACGAN-Mod-TAC.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================85/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ACGAN-Mod-TAC-train-2022_03_06_02_22_58 -cfg ./src/configs/CIFAR10/ACGAN-Mod-TAC.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================86/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ACGAN-Mod-TAC-train-2022_03_06_02_22_58 -cfg ./src/configs/CIFAR10/ACGAN-Mod-TAC.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================87/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ACGAN-Mod-TAC-train-2022_03_06_02_24_25 -cfg ./src/configs/CIFAR10/ACGAN-Mod-TAC.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================88/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ACGAN-Mod-TAC-train-2022_03_06_02_24_25 -cfg ./src/configs/CIFAR10/ACGAN-Mod-TAC.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================89/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ACGAN-Mod-TAC-train-2022_03_06_02_24_25 -cfg ./src/configs/CIFAR10/ACGAN-Mod-TAC.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================90/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ProjGAN-train-2022_03_06_02_21_25 -cfg ./src/configs/CIFAR10/ProjGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================91/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ProjGAN-train-2022_03_06_02_21_25 -cfg ./src/configs/CIFAR10/ProjGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================92/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ProjGAN-train-2022_03_06_02_21_25 -cfg ./src/configs/CIFAR10/ProjGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================93/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ProjGAN-train-2022_03_06_02_23_13 -cfg ./src/configs/CIFAR10/ProjGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================94/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ProjGAN-train-2022_03_06_02_23_13 -cfg ./src/configs/CIFAR10/ProjGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================95/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ProjGAN-train-2022_03_06_02_23_13 -cfg ./src/configs/CIFAR10/ProjGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================96/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ProjGAN-train-2022_03_06_02_24_36 -cfg ./src/configs/CIFAR10/ProjGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================97/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ProjGAN-train-2022_03_06_02_24_36 -cfg ./src/configs/CIFAR10/ProjGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================98/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ProjGAN-train-2022_03_06_02_24_36 -cfg ./src/configs/CIFAR10/ProjGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================99/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-train-2022_03_06_02_21_44 -cfg ./src/configs/CIFAR10/SNGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================100/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-train-2022_03_06_02_21_44 -cfg ./src/configs/CIFAR10/SNGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================101/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-train-2022_03_06_02_21_44 -cfg ./src/configs/CIFAR10/SNGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================102/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-train-2022_03_06_02_23_48 -cfg ./src/configs/CIFAR10/SNGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================103/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-train-2022_03_06_02_23_48 -cfg ./src/configs/CIFAR10/SNGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================104/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-train-2022_03_06_02_23_48 -cfg ./src/configs/CIFAR10/SNGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================105/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-train-2022_03_06_02_24_46 -cfg ./src/configs/CIFAR10/SNGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================106/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-train-2022_03_06_02_24_46 -cfg ./src/configs/CIFAR10/SNGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================107/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SNGAN-train-2022_03_06_02_24_46 -cfg ./src/configs/CIFAR10/SNGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================108/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SAGAN-train-2022_03_06_02_22_12 -cfg ./src/configs/CIFAR10/SAGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================109/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SAGAN-train-2022_03_06_02_22_12 -cfg ./src/configs/CIFAR10/SAGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================110/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SAGAN-train-2022_03_06_02_22_12 -cfg ./src/configs/CIFAR10/SAGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================111/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SAGAN-train-2022_03_06_02_23_57 -cfg ./src/configs/CIFAR10/SAGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================112/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SAGAN-train-2022_03_06_02_23_57 -cfg ./src/configs/CIFAR10/SAGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================113/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SAGAN-train-2022_03_06_02_23_57 -cfg ./src/configs/CIFAR10/SAGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================114/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SAGAN-train-2022_03_06_02_24_49 -cfg ./src/configs/CIFAR10/SAGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================115/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SAGAN-train-2022_03_06_02_24_49 -cfg ./src/configs/CIFAR10/SAGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================116/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-SAGAN-train-2022_03_06_02_24_49 -cfg ./src/configs/CIFAR10/SAGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================117/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Mod-train-2022_01_13_01_23_24 -cfg ./src/configs/CIFAR10/BigGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================118/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Mod-train-2022_01_13_01_23_24 -cfg ./src/configs/CIFAR10/BigGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================119/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Mod-train-2022_01_13_01_23_24 -cfg ./src/configs/CIFAR10/BigGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================120/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Mod-train-2022_01_13_01_23_55 -cfg ./src/configs/CIFAR10/BigGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================121/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Mod-train-2022_01_13_01_23_55 -cfg ./src/configs/CIFAR10/BigGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================122/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Mod-train-2022_01_13_01_23_55 -cfg ./src/configs/CIFAR10/BigGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================123/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Mod-train-2022_01_13_11_18_11 -cfg ./src/configs/CIFAR10/BigGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================124/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Mod-train-2022_01_13_11_18_11 -cfg ./src/configs/CIFAR10/BigGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================125/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-BigGAN-Mod-train-2022_01_13_11_18_11 -cfg ./src/configs/CIFAR10/BigGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================126/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ContraGAN-train-2022_01_13_01_24_34 -cfg ./src/configs/CIFAR10/ContraGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================127/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ContraGAN-train-2022_01_13_01_24_34 -cfg ./src/configs/CIFAR10/ContraGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================128/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ContraGAN-train-2022_01_13_01_24_34 -cfg ./src/configs/CIFAR10/ContraGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================129/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ContraGAN-train-2022_01_13_01_25_00 -cfg ./src/configs/CIFAR10/ContraGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================130/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ContraGAN-train-2022_01_13_01_25_00 -cfg ./src/configs/CIFAR10/ContraGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================131/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ContraGAN-train-2022_01_13_01_25_00 -cfg ./src/configs/CIFAR10/ContraGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================132/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ContraGAN-train-2022_01_13_11_17_17 -cfg ./src/configs/CIFAR10/ContraGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================133/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ContraGAN-train-2022_01_13_11_17_17 -cfg ./src/configs/CIFAR10/ContraGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================134/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ContraGAN-train-2022_01_13_11_17_17 -cfg ./src/configs/CIFAR10/ContraGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================135/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ReACGAN-train-2022_01_13_01_26_09 -cfg ./src/configs/CIFAR10/ReACGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================136/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ReACGAN-train-2022_01_13_01_26_09 -cfg ./src/configs/CIFAR10/ReACGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================137/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ReACGAN-train-2022_01_13_01_26_09 -cfg ./src/configs/CIFAR10/ReACGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================138/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ReACGAN-train-2022_01_13_01_26_35 -cfg ./src/configs/CIFAR10/ReACGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================139/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ReACGAN-train-2022_01_13_01_26_35 -cfg ./src/configs/CIFAR10/ReACGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================140/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ReACGAN-train-2022_01_13_01_26_35 -cfg ./src/configs/CIFAR10/ReACGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================141/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ReACGAN-train-2022_01_24_23_46_59 -cfg ./src/configs/CIFAR10/ReACGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================142/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ReACGAN-train-2022_01_24_23_46_59 -cfg ./src/configs/CIFAR10/ReACGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================143/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -std_stat -std_max 128 -std_step 128 -best --seed 1234 -ifid -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-ReACGAN-train-2022_01_24_23_46_59 -cfg ./src/configs/CIFAR10/ReACGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================144/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-train-2022_01_24_23_49_42 -cfg ./src/configs/CIFAR10/StyleGAN2.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================145/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-train-2022_01_24_23_49_42 -cfg ./src/configs/CIFAR10/StyleGAN2.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================146/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-train-2022_01_24_23_49_42 -cfg ./src/configs/CIFAR10/StyleGAN2.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================147/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-train-2022_01_24_23_50_27 -cfg ./src/configs/CIFAR10/StyleGAN2.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================148/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-train-2022_01_24_23_50_27 -cfg ./src/configs/CIFAR10/StyleGAN2.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================149/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-train-2022_01_24_23_50_27 -cfg ./src/configs/CIFAR10/StyleGAN2.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================150/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-train-2022_01_24_23_51_10 -cfg ./src/configs/CIFAR10/StyleGAN2.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================151/243 completed =============
MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 OMP_NUM_THREADS=12 CUDA_VISIBLE_DEVICES=0 python src/main.py --pre_resizer wo_resize --post_resizer tailored -best --seed 1234 -ifid -mpc -data /root/ext_data/data/CIFAR10 -save ../studiogan/ -ckpt /root/ext_data/studiogan_ckpt/CIFAR10/checkpoints/CIFAR10-StyleGAN2-train-2022_01_24_23_51_10 -cfg ./src/configs/CIFAR10/StyleGAN2.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================152/243 completed =============
