python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 256 -std_step 256 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-SNGAN-train-2022_03_08_03_19_50 -cfg ./src/configs/Papa_ImageNet/SNGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================1/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 256 -std_step 256 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-SNGAN-train-2022_03_08_03_19_50 -cfg ./src/configs/Papa_ImageNet/SNGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================2/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 256 -std_step 256 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-SNGAN-train-2022_03_08_03_19_50 -cfg ./src/configs/Papa_ImageNet/SNGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================3/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 256 -std_step 256 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-SNGAN-train-2022_03_08_22_13_02 -cfg ./src/configs/Papa_ImageNet/SNGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================4/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 256 -std_step 256 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-SNGAN-train-2022_03_08_22_13_02 -cfg ./src/configs/Papa_ImageNet/SNGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================5/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 256 -std_step 256 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-SNGAN-train-2022_03_08_22_13_02 -cfg ./src/configs/Papa_ImageNet/SNGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================6/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 256 -std_step 256 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-SAGAN-train-2022_03_09_00_55_23 -cfg ./src/configs/Papa_ImageNet/SAGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================7/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 256 -std_step 256 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-SAGAN-train-2022_03_09_00_55_23 -cfg ./src/configs/Papa_ImageNet/SAGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================8/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 256 -std_step 256 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-SAGAN-train-2022_03_09_00_55_23 -cfg ./src/configs/Papa_ImageNet/SAGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================9/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-BigGAN-train-2022_02_23_16_26_07 -cfg ./src/configs/Papa_ImageNet/BigGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================10/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-BigGAN-train-2022_02_23_16_26_07 -cfg ./src/configs/Papa_ImageNet/BigGAN.yaml --eval_backbone SwAV_torch  -metrics none
echo ==================11/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-BigGAN-train-2022_02_23_16_26_07 -cfg ./src/configs/Papa_ImageNet/BigGAN.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================12/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored  -std_stat -std_max 1024 -std_step 1024 -best --seed 1234 -ifid -data /home/mgkang/data/Papa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Papa_ImageNet/checkpoints/Papa_ImageNet-BigGAN-train-2022_02_23_16_26_09 -cfg ./src/configs/Papa_ImageNet/BigGAN.yaml --eval_backbone InceptionV3_tf  -metrics none
echo ==================13/36 completed =============
python src/main.py --pre_resizer lanczos --post_resizer tailored -best --seed 1234 -ifid -mpc  -data /home/mgkang/data/Grandpa_ImageNet -save ../studiogan/ -ckpt /home/mgkang/joong/eval_temp/studiogan_ckpts/Grandpa_ImageNet/checkpoints/Grandpa_ImageNet-StyleGAN2-SPD-train-2022_02_24_15_37_30 -cfg ./src/configs/Grandpa_ImageNet/StyleGAN2-SPD.yaml --eval_backbone Swin-T_torch  -metrics none
echo ==================33/36 completed =============
